[build]
builder = "DOCKERFILE"
watchPatterns = ["backend/**/*", "frontend/**/*"]

[deploy]
startCommand = "python /app/backend/main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1
healthcheckInterval = "30s"
healthcheckMaxRetries = 10
startupDelay = "60s"

[env]
PYTHON_VERSION = "3.9"
NODE_VERSION = "16"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
DEBUG = "False"
