[build]
builder = "DOCKERFILE"
watchPatterns = ["backend/**/*", "frontend/**/*"]

[deploy]
startCommand = "python backend/main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.9"
NODE_VERSION = "16"
