[build]
builder = "DOCKERFILE"
watchPatterns = ["backend/**/*", "frontend/**/*"]

[deploy]
startCommand = "python backend/main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1
healthcheckInterval = "15s"
healthcheckMaxRetries = 5

[env]
PYTHON_VERSION = "3.9"
NODE_VERSION = "16"
PYTHONUNBUFFERED = "1"
